# Use postgres/example user/password credentials
version: '3.1'

services:
  searchengine:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  db:
    image: postgres
    restart: unless-stopped
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: speiseplan
      POSTGRES_PASSWORD: happymealtime

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
